### ISSUE TITLE
sviewer et epsg:2154

### ISSUE THREAD

**Issue by bchartier** [georchestra/sviewer#25]
En raison de services WMS ne supportant pas EPSG:3857 mais plutôt EPSG:2154, j'ai essayé de paramétrer sviewer pour que la carte soit en EPSG:2154. Je me suis rendu compte que ce n'est pas si simple que cela en avait l'air au premier abord.

Est-ce que cela vous semblerait une bonne idée que je fasse légèrement évoluer le code pour que l'on puisse plus facilement déployer un sviewer en Lambert 93 ?

Pour l'instant, mon sviewer bricolé EPSG:2154 (avec un contexte contenant des données sur l'éolien) est visible là :
http://www.geopicardie.fr/files/sviewer2154/?wmc=http%3A%2F%2Fwww.geopicardie.fr%2Fmapfishapp%2Fws%2Fwmc%2Fgeodocddd753dea6ab0874885ba15a81e5a9d7.wmc

**Comment by fphg** [comment]
Le sviewer a fait l'exact chemin inverse.

Si cela ne pèse pas sur le code (ce serait plutôt l'inverse je pense)
pas de souci.

Evidemment il serait préférable demander aux gestionnaires de supporter
3857.

**Comment by bchartier** [comment]
> Evidemment il serait préférable demander aux gestionnaires de supporter
> 3857.

Fait auprès de GéoPicardie qui doit ensuite remonter la demande auprès des gestionnaires (processus opaque pour moi).

**Comment by bchartier** [comment]
Mes modifs sont disponibles là :
https://github.com/neogeo-technologies/geopicardie-sviewer

Le code n'a pas été alourdi.
J'ai mis en commentaires quelques lignes au début de sviewer.js car apparemment elles ne sont pas du tout utilisées et elles faisaient planter sviewer quand on spécifiait du epsg:2154.

On peut maintenant définir simplement le SRS de la carte dans un fichier customConfig.js.
Ce qui permet d'utiliser le paramètre c dans la requête Get qui lance le sviewer pour changer de SRS sans redéployer un second sviewer.
Dans le repository de Neogeo j'ai mis la configuration pour GéoPicardie avec deux fichiers de config qui illustrent cela : customConfig_geopic2154.js et customConfig_geopic3857.js

En passant, j'ai retiré les couches MapQuest qui ne fonctionnent plus aussi simplement qu'avant et j'ai ajouté la couche OSM d'openstreetmap.org et une couche OSM de GéoPicardie dans la config par défaut.

J'ai vérifié que le chargement des KML fonctionne toujours en epsg:2154.

Il faudrait peut-être que quelqu'un d'autre que moi fasse des tests avec ce code avant de le basculer dans le projet georchestra/sviewer. Dites-moi si je peux faire un pull request.

**Comment by bchartier** [comment]
Mon pull request : #26
